Remove unnecessary loop

diff --git a/dc b/dc
--- a/dc
+++ b/dc
@@ -670,21 +670,19 @@ function shell(){
     else
         printf "Accessing shell for the following service: %s \n" "$1"
         tmp_stack_files_age
-        for SERVICE in "$1";
-        do
-            DC_CMD_PARAM="exec ${SERVICE} /bin/sh"
-            if grep -r -q -x "${SERVICE}" "${TMP_DIR}"; then
-                STACK_NAME=$(basename "$(grep -r -x "${SERVICE}" "${TMP_DIR}" | cut -d : -f 1 )")
-                STACK="${DC_DIR}/${STACK_NAME}"
-                verbose_stack "${STACK}" "${STACK_NAME}" "${SERVICE}"
-                cd "${STACK}" || { echo "cd failed"; exit 1; }
-                create_env_file "${STACK}" "${STACK_NAME}"
-                dc_cmd_create "${DC_CMD_PARAM}"
-                cd - > /dev/null || { echo "cd failed"; exit 1; }
-            else
-                printf "ERROR: Service %s was not found in any of the stacks. Does it show up when you run %bdc list%b? \n" "${SERVICE}" "${RED}" "${NC}"
-            fi
-        done
+        SERVICE="$1"
+        DC_CMD_PARAM="exec ${SERVICE} /bin/sh"
+        if grep -r -q -x "${SERVICE}" "${TMP_DIR}"; then
+            STACK_NAME=$(basename "$(grep -r -x "${SERVICE}" "${TMP_DIR}" | cut -d : -f 1 )")
+            STACK="${DC_DIR}/${STACK_NAME}"
+            verbose_stack "${STACK}" "${STACK_NAME}" "${SERVICE}"
+            cd "${STACK}" || { echo "cd failed"; exit 1; }
+            create_env_file "${STACK}" "${STACK_NAME}"
+            dc_cmd_create "${DC_CMD_PARAM}"
+            cd - > /dev/null || { echo "cd failed"; exit 1; }
+        else
+            printf "ERROR: Service %s was not found in any of the stacks. Does it show up when you run %bdc list%b? \n" "${SERVICE}" "${RED}" "${NC}"
+        fi
     fi
     }
 
