Updated with suggestions from ChatGPT

diff --git a/dc b/dc
--- a/dc
+++ b/dc
@@ -6,7 +6,7 @@
 set -m
 
 # VERSION
-export DC_VERSION=v3.4.6
+export DC_VERSION=v3.4.7
 
 ###### VARIABLES
 if [[ -z "${DC_DIR}" ]]; then
@@ -328,33 +328,50 @@ function update(){
     LATEST_VERSION=$(curl --silent https://api.github.com/repos/brhahlen/dc/releases/latest | grep -Po '"tag_name": "\K.*?(?=")')
     export LATEST_VERSION
     export UPDATE_TMP=/tmp/dc_update
-    printf "You are on version %s of %bdc%b \n" "${DC_VERSION}" "${RED}" "${NC}"
-        if [ ! "$(printf '%s\n' "${LATEST_VERSION}" "${DC_VERSION}" | sort -V | head -n1)" = "${LATEST_VERSION}" ]; then
-            printf "Version %b%s%b of %bdc%b is available and will be downloaded and installed \n" "${BLUE}" "${LATEST_VERSION}" "${NC}" "${RED}" "${NC}"
-            if [ ! -d ${UPDATE_TMP} ]; then
-                printf "%s does not exist. Creating... \n" "${UPDATE_TMP}"
-                mkdir -p "${UPDATE_TMP}"
-            else
-                printf "Cleanup previous update files... \n"
-                rm -rf "${UPDATE_TMP}"
-                mkdir "${UPDATE_TMP}"
-            fi
-            printf "Downloading... \n"
-            if wget -V | grep -q Wget2 ; then
-            wget -q --force-progress https://github.com/brhahlen/dc/releases/download/"${LATEST_VERSION}"/dc-release.zip -O "${UPDATE_TMP}"/dc-release.zip
-            else
-            wget -q --show-progress https://github.com/brhahlen/dc/releases/download/"${LATEST_VERSION}"/dc-release.zip -O "${UPDATE_TMP}"/dc-release.zip
-            fi
-            printf "Extracting... \n"
-            unzip -q "${UPDATE_TMP}"/dc-release.zip -d "${UPDATE_TMP}"
-            printf "Updating... \n"
-            cd "${UPDATE_TMP}" || { echo "cd failed"; exit 1; }
-            /usr/bin/bash "${UPDATE_TMP}"/dc install
-            cd - > /dev/null || { echo "cd failed"; exit 1; }
-            printf "Done \n"
+    printf "You are on version %s of %bdc%b \\n" "${DC_VERSION}" "${RED}" "${NC}"
+
+    if [ ! "$(printf '%s\n' "${LATEST_VERSION}" "${DC_VERSION}" | sort -V | head -n1)" = "${LATEST_VERSION}" ]; then
+        printf "Version %b%s%b of %bdc%b is available and will be downloaded and installed \\n" "${BLUE}" "${LATEST_VERSION}" "${NC}" "${RED}" "${NC}"
+        if [ ! -d "${UPDATE_TMP}" ]; then
+            printf "%s does not exist. Creating... \\n" "${UPDATE_TMP}"
+            mkdir -p "${UPDATE_TMP}"
         else
-            printf "This is the latest version, no update needed \n"
+            printf "Cleanup previous update files... \\n"
+            rm -rf "${UPDATE_TMP}"
+            mkdir "${UPDATE_TMP}"
         fi
+
+        printf "Downloading... \\n"
+        if wget -V | grep -q Wget2 ; then
+            wget -q --force-progress https://github.com/brhahlen/dc/releases/download/"${LATEST_VERSION}"/dc-release.zip -O "${UPDATE_TMP}"/dc-release.zip
+        else
+            wget -q --show-progress https://github.com/brhahlen/dc/releases/download/"${LATEST_VERSION}"/dc-release.zip -O "${UPDATE_TMP}"/dc-release.zip
+        fi
+
+        if [ $? -ne 0 ]; then
+            echo "Error downloading file"
+            exit 1
+        fi
+
+        printf "Extracting... \\n"
+        unzip -q "${UPDATE_TMP}"/dc-release.zip -d "${UPDATE_TMP}"
+        if [ $? -ne 0 ]; then
+            echo "Error extracting file"
+            exit 1
+        fi
+
+        printf "Updating... \\n"
+        cd "${UPDATE_TMP}" || { echo "cd failed"; exit 1; }
+        /usr/bin/bash "${UPDATE_TMP}"/dc install
+        if [ $? -ne 0 ]; then
+            echo "Update script execution failed"
+            exit 1
+        fi
+        cd - > /dev/null || { echo "cd failed"; exit 1; }
+        printf "Done \\n"
+    else
+        printf "This is the latest version, no update needed \\n"
+    fi
 }
 
 ##################################################
