More verbosity

diff --git a/dc b/dc
--- a/dc
+++ b/dc
@@ -435,10 +435,13 @@ function list(){
 while getopts ":v" opt; do
   case $opt in
     v)
-      echo "-v was triggered!"
-      shift 1
+      echo "-v was triggered!" >&2
       ;;
-    *)
+    )
+      echo "Invalid option: -$OPTARG" >&2
+      ;;
+  esac
+done
 case ${1} in
 # ----------- install ------------
     "install")
@@ -532,6 +535,3 @@ case ${1} in
         show_usage
         ;;
 esac
-
-esac
-done
